# Generated by Django 3.2.7 on 2021-10-03 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210927_1525'),
        ('blog', '0004_auto_20190713_2354'),
    ]

    operations = [
    ]
